In [1]:
import numpy as np

# ファイルをロード
data = np.load("MR_Lx_24_pg_0.75.npy", allow_pickle=True)

# まず型を確認
print(type(data))

# ndarray の場合
print("shape:", data.shape)
print("dtype:", data.dtype)

# 小さいならそのまま表示
print(data)

# 大きい配列なら一部だけ表示
print(data[:10])

# 辞書形式（np.save ではなく np.savez のような場合）なら
if isinstance(data, np.lib.npyio.NpzFile):
    print("keys:", data.files)
    for k in data.files:
        print(k, data[k].shape)


<class 'numpy.ndarray'>
shape: (1728, 3456)
dtype: uint32
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
